version: '3'
services: 
  php:
    container_name: php-fpm
    build :
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/var/www/html
    networks:
     - nginx_docker

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
     - 80:80
    depends_on:
     - php
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
     - nginx_docker

networks:
  nginx_docker:
    driver: bridge
  
